defaults:
  - layersconf: layers
  - regularizersconf: regularizers

layers:
  - ${modelconf.layersconf.input_layer}
  - ${modelconf.layersconf.Random_Flip}
  - ${modelconf.layersconf.Random_Brightness}
  - ${modelconf.layersconf.Random_Contrast}
  - ${modelconf.layersconf.rescaling_layer}
  - ${modelconf.layersconf.Conv2D_1}
  - ${modelconf.layersconf.MaxPooling2D}
  - ${modelconf.layersconf.Conv2D_2}
  - ${modelconf.layersconf.MaxPooling2D}
  - ${modelconf.layersconf.Conv2D_3}
  - ${modelconf.layersconf.MaxPooling2D}
  - ${modelconf.layersconf.Flatten}
  - ${modelconf.layersconf.Dense1}
  - ${modelconf.layersconf.Dropout1}
  - ${modelconf.layersconf.Dense2}
  - ${modelconf.layersconf.Dropout2}
  - ${modelconf.layersconf.Out_layer}

layer_list:
  _target_: builtins.list
  _args_:
    - ${modelconf.layers}

model:
  _target_: tensorflow.keras.models.Sequential
  layers: ${modelconf.layer_list}