defaults:
  - modelconf: 3LayerConv
  - dataconf: data

epochs: 2
batch_size: 24
optimizer:
  _target_: tensorflow.keras.optimizers.Adam
  learning_rate: 0.00455
  beta_1: 0.9
  beta_2: 0.999
  epsilon: 0.0000001


loss:
  _target_: tensorflow.keras.losses.SparseCategoricalCrossentropy
  from_logits: False

metrics:
  - accuracy

metrics_list:
  _target_: builtins.list
  _args_:
    - ${metrics}
