defaults:
  - modelconf: 3LayerConv
  - dataconf: data

epochs: 2
batch_size: 32
optimizer: adam
loss:
  _target_: tensorflow.keras.losses.SparseCategoricalCrossentropy
  from_logits: False

metrics:
  - accuracy

metrics_list:
  _target_: builtins.list
  _args_:
    - ${metrics}
