defaults:
  - layersconf: layers

layers:
  - ${modelconf.layersconf.input_layer}
  - ${modelconf.layersconf.rescaling_layer}
  - ${modelconf.layersconf.2Dconv_16f}
  - ${modelconf.layersconf.MaxPooling2D}
  - ${modelconf.layersconf.2Dconv_32f}
  - ${modelconf.layersconf.MaxPooling2D}
  - ${modelconf.layersconf.2Dconv_64f}
  - ${modelconf.layersconf.MaxPooling2D}
  - ${modelconf.layersconf.Flatten}
  - ${modelconf.layersconf.Dense128}
  - ${modelconf.layersconf.Out_layer}

layer_list:
  _target_: builtins.list
  _args_:
    - ${modelconf.layers}

model:
  _target_: tensorflow.keras.models.Sequential
  layers: ${modelconf.layer_list}