input_layer:
  _target_: tensorflow.keras.layers.InputLayer
  input_shape: ${input_shape_tuple}
  dtype: uint8

rescaling_layer:
  _target_: tensorflow.keras.layers.Rescaling
  scale: ${eval:'1/255'}

Conv2D_1:
  _target_: tensorflow.keras.layers.Conv2D
  filters: 16
  kernel_size: 3
  padding: same
  activation: relu

Conv2D_2:
  _target_: tensorflow.keras.layers.Conv2D
  filters: 32
  kernel_size: 3
  padding: same
  activation: relu

Conv2D_3:
  _target_: tensorflow.keras.layers.Conv2D
  filters: 64
  kernel_size: 3
  padding: same
  activation: relu

Flatten:
  _target_: tensorflow.keras.layers.Flatten

MaxPooling2D:
  _target_: tensorflow.keras.layers.MaxPooling2D

Dense128:
  _target_: tensorflow.keras.layers.Dense
  units: 128
  activation: relu

Out_layer:
  _target_: tensorflow.keras.layers.Dense
  units: 2
  activation: 'sigmoid'