input_layer:
  _target_: tensorflow.keras.layers.InputLayer
  input_shape: ${dataconf.input_shape_tuple}
  dtype: uint8

rescaling_layer:
  _target_: tensorflow.keras.layers.Rescaling
  scale: ${eval:'1/255'}

Random_Flip:
  _target_: tensorflow.keras.layers.RandomFlip
  mode: horizontal_and_vertical

Random_Rotation:
  _target_: tensorflow.keras.layers.RandomRotation
  factor: 0.2

Conv2D_1:
  _target_: tensorflow.keras.layers.Conv2D
  filters: 16
  kernel_size: 5
  padding: same
  activation: relu
  kernel_regularizer: ${modelconf.regularizersconf.L1L2_regularizer}
  
Conv2D_2:
  _target_: tensorflow.keras.layers.Conv2D
  filters: 8
  kernel_size: 5
  padding: same
  activation: relu
  kernel_regularizer: ${modelconf.regularizersconf.L1L2_regularizer}
  
Conv2D_3:
  _target_: tensorflow.keras.layers.Conv2D
  filters: 8
  kernel_size: 5
  padding: same
  activation: relu
  kernel_regularizer: ${modelconf.regularizersconf.L1L2_regularizer}

Flatten:
  _target_: tensorflow.keras.layers.Flatten

MaxPooling2D:
  _target_: tensorflow.keras.layers.MaxPooling2D

Dense128:
  _target_: tensorflow.keras.layers.Dense
  units: 128
  activation: relu

Dropout:
  _target_: tensorflow.keras.layers.Dropout
  rate: 0

Out_layer:
  _target_: tensorflow.keras.layers.Dense
  units: 2
  activation: 'sigmoid'